[tool.mypy]
no_incremental = true
ignore_missing_imports = true
disallow_untyped_defs = true
disallow_incomplete_defs = true
disallow_subclassing_any = true
disallow_any_generics = true
no_implicit_optional = true
warn_redundant_casts = true
warn_unused_ignores = true
warn_unreachable = true
allow_untyped_decorators = true
exclude = [
    "external/",
    "tests/",
    ".tmp/",
    ".venv/"
]

[tool.pytest.ini_options]
pythonpath = "."
minversion = "6.0"
addopts = "--cov=adaptive_pruning/ --cov-report=term-missing --cov-report=xml"
testpaths = [
    "tests",
]

[tool.ruff]
line-length = 120
target-version = "py312"

extend-exclude = ["external/"]

# Enable the pycodestyle (`E`) and Pyflakes (`F`) rules by default.
# Unlike Flake8, Ruff doesn't enable pycodestyle warnings (`W`) or
# McCabe complexity (`C901`) by default.
lint.select = ["E", "F"]
lint.ignore = []

# Allow autofix for all enabled rules (when `--fix`) is provided.
lint.fixable = ["ALL"]
lint.unfixable = []

exclude = [
    ".bzr",
    ".direnv",
    ".eggs",
    ".git",
    ".git-rewrite",
    ".hg",
    ".mypy_cache",
    ".nox",
    ".pants.d",
    ".pytype",
    ".ruff_cache",
    ".svn",
    ".tox",
    ".venv",
    "__pypackages__",
    "_build",
    "buck-out",
    "build",
    "dist",
    "node_modules",
    "venv",

    "tests",
    ".tmp",
    "__init__.py",
]


[tool.isort]
profile = "black"
extend_skip = ["external/"]
line_length = 120
lines_after_imports = 2
combine_as_imports = true
default_section = "THIRDPARTY"
known_first_party = "adaptive_pruning,tests"

[tool.black]
line-length = 120
target-version = ['py312']
extend-exclude = "external/"
